[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "797c0c9ebd4e55dfe534cbccbc496fef677a825c"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "71ea97df60604474f4ea022cf912383a6cb015a9935505f4d65e1db04510d3f4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "11d085e6368f81c85655a3b0f848a0656b6d86d7"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a805be65e7c509d3a52bed1d87f05548ef9a6b890d0401ef7ad3ae5ddc90f897"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "cc7b14371d41b0aa98e3bf39dc30dea1d8d38a95"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "f7e8eb8ea7710889c832e18bb4a893ebe1f95da02d70998f656cbf4b32ee5116"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "de7d5b782c4308347cabe7a8e9fe9d4bcbba9e75"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b8dc7f586a93f1d0bce308c5f403455580ff512fb4d344d3e44bd8b81d00c4d1"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "f0b242d5ec70ffa192d40736c13fe0b92ef49074"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "9c52b4fc5670cf031172bf7db28317e29fd7af0fb9c286adf53e7a5814b94df0"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "621cd3bde64a7f04737f20edb608342c20cefef1"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b63be0824a42352eeb732488d629e9edaa6700f30126d1fd90adbb91d86814f5"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "382d68de5642eec643713a83a516ccf24e182c79"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "f1ef98158e57ddb96f037031a53e2d018c1a1c395b1aed14ef9ded6a810c1a58"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "2234bd5dfa33360dd759e8a724e11b771225ca6f"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "8480cfc3b61d60a6071cdd1bf85a4850b18bae739761b0f3a1f76d8ca4a72b4c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "6747ff3ca6f8466cc5461023c8b698ac3ee0a9f1"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "fdb58baef38f63cbf8aca0889b95c6c926c76545bcba82e2c84c84afc9c843ad"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.arm-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "4b443ae34cbaf9245354d0878fd4cda047c1a283"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a4247bb028b4907fdc99b4fc0c867bbab36b3b633d395aaceb105aec33de450c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "565e1e39ac63cead8e8164f3db387b4c4b607d14"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "bc5daa62728a7c8cb6fc7e9e845e324a51df025480f8dad3a33718f77bde34a0"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.arm-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "040ca3d4bea7870cbee3fca97f8e369254ad5d95"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "f3e2656103d40ad0211bf4bfc52f3126352d5382a46f7bdb85aaf08402fdd39b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "10fe8cb1187eafbe01a815af8c1b49abe895e087"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "44587c9a2a7cbc6d4eefa49b04afd54530541a625509a15ccbdbdb473121263b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+5/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
